#!/usr/bin/env bash
# =============================================================================
# setup_cyclonedds_shm.sh
#
# Configure CycloneDDS to use Iceoryx SHARED-MEMORY (zero-copy) transport for
# same-host delivery. Without this, large messages (e.g. 1440x928x3 ~= 4 MB
# camera images) are serialized + fragmented + copied over loopback UDP
# *separately for every subscriber*. That per-subscriber cost saturates CPU /
# memory bandwidth and, through CARLA's synchronous-mode tick, collapses sim
# FPS (measured 32 -> 8-12 Hz the moment a 6-camera consumer subscribes).
#
# Shared memory delivers one chunk to N local readers, removing that cost
# (publisher CPU for a 4 MB image @20Hz with 6 subscribers: ~24% UDP -> ~2% SHM).
#
# What this does (idempotent — safe to re-run):
#   1. ~/.config/cyclonedds/cyclonedds.xml   (SharedMemory enabled + UDP tuning)
#   2. ~/.config/iceoryx/roudi_config.toml   (mempools sized for 4 MB images)
#   3. ~/.config/systemd/user/iox-roudi.service  (runs the RouDi SHM daemon)
#   4. ~/.bashrc                              (exports RMW only — see below)
#   5. enables + starts the iox-roudi user service
#
# NOTE: SHM only engages when BOTH publisher and subscriber have CYCLONEDDS_URI
# set, and RouDi is running. CYCLONEDDS_URI is therefore set ONLY in the launch
# files of the two endpoints on the heavy camera path (carla_telemetry_cpp +
# rendering_node) — NOT globally in ~/.bashrc. Exporting it globally would route
# every DDS writer of every node through iceoryx and exhaust RouDi's
# compile-time 512-publisher cap (IOX_MAX_PUBLISHERS), crashing nodes with
# POSH__RUNTIME_ROUDI_PUBLISHER_LIST_FULL. Only RMW_IMPLEMENTATION is global
# (it uses no iceoryx ports but must be uniform for discovery to work).
# =============================================================================
set -euo pipefail

ROS_DISTRO="${ROS_DISTRO:-humble}"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
CYCLONE_XML="$CFG/cyclonedds/cyclonedds.xml"
ROUDI_TOML="$CFG/iceoryx/roudi_config.toml"
SERVICE_DIR="$CFG/systemd/user"
SERVICE="$SERVICE_DIR/iox-roudi.service"

say() { printf '\033[0;32m[shm-setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[shm-setup] WARN:\033[0m %s\n' "$*"; }

# --- Detect Iceoryx / RouDi locations (works regardless of username/distro) ---
ROUDI_BIN="$(command -v iox-roudi 2>/dev/null || true)"
[ -z "$ROUDI_BIN" ] && [ -x "/opt/ros/$ROS_DISTRO/bin/iox-roudi" ] && ROUDI_BIN="/opt/ros/$ROS_DISTRO/bin/iox-roudi"
if [ -z "$ROUDI_BIN" ]; then
    warn "iox-roudi not found. Install iceoryx (e.g. ros-$ROS_DISTRO-iceoryx-posh) and re-run."
    exit 1
fi

POSH_CFG_LIB="$(find "/opt/ros/$ROS_DISTRO" -name 'libiceoryx_posh_config.so*' 2>/dev/null | head -1 || true)"
if [ -n "$POSH_CFG_LIB" ]; then
    ICEORYX_LIB_DIR="$(dirname "$POSH_CFG_LIB")"
else
    ICEORYX_LIB_DIR="/opt/ros/$ROS_DISTRO/lib/x86_64-linux-gnu"
    warn "Could not locate libiceoryx_posh_config.so; assuming $ICEORYX_LIB_DIR"
fi

say "ROS_DISTRO=$ROS_DISTRO"
say "RouDi binary: $ROUDI_BIN"
say "Iceoryx lib dir: $ICEORYX_LIB_DIR"

mkdir -p "$(dirname "$CYCLONE_XML")" "$(dirname "$ROUDI_TOML")" "$SERVICE_DIR"

# --- 1. CycloneDDS config -----------------------------------------------------
# Only generate when absent. If it already exists it is left untouched so an
# in-place tuner (scripts/tune_cyclone_xml.py) can preserve custom settings.
if [ -f "$CYCLONE_XML" ]; then
    say "$CYCLONE_XML exists — leaving as-is (tune in place, not overwriting)"
else
cat > "$CYCLONE_XML" <<'EOF'
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by setup_cyclonedds_shm.sh. Enables Iceoryx shared-memory
     (zero-copy) transport for same-host delivery; UDP settings are the
     cross-host / fallback path. Requires the iox-roudi daemon to be running. -->
<CycloneDDS xmlns="https://cdds.io/config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <AllowMulticast>true</AllowMulticast>
            <FragmentSize>4096 B</FragmentSize>
        </General>
        <Internal>
            <SocketReceiveBufferSize min="120 MB"/>
            <SocketSendBufferSize min="120 MB"/>
            <Watermarks>
                <WhcHigh>100MB</WhcHigh>
            </Watermarks>
        </Internal>
        <SharedMemory>
            <Enable>true</Enable>
            <LogLevel>info</LogLevel>
        </SharedMemory>
    </Domain>
</CycloneDDS>
EOF
say "wrote $CYCLONE_XML"
fi

# --- 2. Iceoryx RouDi mempool config -----------------------------------------
# 6 MB pool covers 4 MB camera images (+CDR/ROS overhead); 16 MB pool covers
# larger point clouds / costmaps. Anything bigger falls back to UDP.
cat > "$ROUDI_TOML" <<'EOF'
# Generated by setup_cyclonedds_shm.sh
[general]
version = 1

[[segment]]

[[segment.mempool]]
size = 256
count = 20000

[[segment.mempool]]
size = 1024
count = 10000

[[segment.mempool]]
size = 16384
count = 3000

[[segment.mempool]]
size = 262144
count = 500

[[segment.mempool]]
size = 1048576
count = 200

[[segment.mempool]]
size = 6291456
count = 96

[[segment.mempool]]
size = 16777216
count = 24
EOF
say "wrote $ROUDI_TOML"

# --- 3. RouDi systemd user service -------------------------------------------
# %h expands to the user's home, so the unit is portable across users.
cat > "$SERVICE" <<EOF
[Unit]
Description=Iceoryx RouDi shared-memory daemon (CycloneDDS zero-copy transport)
Documentation=https://cyclonedds.io/docs/cyclonedds/latest/shared_memory.html
After=default.target

[Service]
Type=simple
Environment=LD_LIBRARY_PATH=$ICEORYX_LIB_DIR:/opt/ros/$ROS_DISTRO/lib
# -m off: a killed/crashed ROS node must not make RouDi tear down shared memory
# for everyone else; nodes come and go freely.
ExecStart=$ROUDI_BIN -c %h/.config/iceoryx/roudi_config.toml -m off -l warning
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
EOF
say "wrote $SERVICE"

# --- 4. ~/.bashrc export: RMW only (idempotent) ------------------------------
# Export ONLY RMW_IMPLEMENTATION globally so the whole graph speaks CycloneDDS
# (it must be uniform or nodes can't discover each other; RMW itself uses no
# iceoryx ports). Do NOT export CYCLONEDDS_URI globally: that routes every DDS
# writer of every node (rosout, parameter_events, discovery) through iceoryx,
# exhausting RouDi's compile-time 512-publisher cap (IOX_MAX_PUBLISHERS) and
# crashing nodes with POSH__RUNTIME_ROUDI_PUBLISHER_LIST_FULL. SHM is scoped to
# the two endpoints that need it (the CARLA camera publisher and the rendering
# node), which set CYCLONEDDS_URI in their own launch files.
BRC="$HOME/.bashrc"
if ! grep -qE '^[[:space:]]*export[[:space:]]+RMW_IMPLEMENTATION' "$BRC" 2>/dev/null; then
    cp "$BRC" "$BRC.bak-cyclonedds.$(date +%s)" 2>/dev/null || true
    cat >> "$BRC" <<'EOF'

# --- CycloneDDS middleware (setup_cyclonedds_shm.sh) ---
# RMW only — CYCLONEDDS_URI (SHM) is set per-node in launch files, NOT globally,
# to avoid exhausting RouDi's 512-publisher cap. See script section 4.
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
EOF
    say "added RMW_IMPLEMENTATION export to $BRC (backup saved)"
else
    say "$BRC already exports RMW_IMPLEMENTATION — left unchanged"
fi

# --- 5. Enable + start the RouDi service --------------------------------------
# Do NOT restart an already-running RouDi: that would invalidate the shared
# memory of every connected node. Only start it if it isn't running.
systemctl --user daemon-reload
systemctl --user enable iox-roudi.service >/dev/null 2>&1 || true
if systemctl --user --quiet is-active iox-roudi.service; then
    say "iox-roudi.service already running (left as-is). To apply config changes"
    say "later when no nodes are connected: systemctl --user restart iox-roudi.service"
else
    systemctl --user start iox-roudi.service
    sleep 3
    if systemctl --user --quiet is-active iox-roudi.service; then
        say "iox-roudi.service is ACTIVE."
    else
        warn "iox-roudi.service did not start. Check: journalctl --user -u iox-roudi.service"
        exit 1
    fi
fi

# RouDi user service stops on logout unless lingering is enabled (needs sudo).
if [ "$(loginctl show-user "$USER" -p Linger --value 2>/dev/null || echo no)" != "yes" ]; then
    warn "Service stops on logout. To keep it across logout/reboot, run:"
    warn "    sudo loginctl enable-linger $USER"
fi

cat <<EOF

[shm-setup] Done. Shared-memory DDS transport is configured.

  Open a NEW terminal (to pick up the ~/.bashrc exports), then launch the sim:
      cd $(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd) && make launch_carla_sim

  Verify a node is actually using SHM (must print a non-empty path):
      tr '\\0' '\\n' < /proc/\$(pgrep -f carla_telemetry_node)/environ | grep CYCLONEDDS_URI
EOF
